QN1)
SUM OF ALL NUMBERS IN MATRIX


In [2]:
import numpy as np

# Example matrix
matrix = np.array([[10,12, 34],
                   [45, 65, 69],
                   [72, 81, 99]])

# Calculate the sum of all values in the matrix
total_sum = np.sum(matrix)

print("The sum of all values in the matrix is:", total_sum)


The sum of all values in the matrix is: 487


QN2)
How to inverse a matrix using NumPy

In [3]:

import numpy as np

# Taking a 3 * 3 matrix
A = np.array([[2, 0, 1],
			[4, -2, 4],
			[2, 5, 7]])

# Calculating the inverse of the matrix
print(np.linalg.inv(A))


[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


3. Find the intersection of two arrays

In [5]:
import numpy as np

def array_intersection(array1, array2):
    return np.intersect1d(array1, array2)

# Example usage
array1 = np.array([1, 21, 33, 45])
array2 = np.array([33, 45, 56, 6])
intersection = array_intersection(array1, array2)
print(intersection)


[33 45]


QN 4)
Multiply a 5x3 matrix by a 3x2 matrix

In [6]:
import numpy as np

# Example matrices
matrix1 = np.random.random((5, 3))
matrix2 = np.random.random((3, 2))

# Matrix multiplication
product = np.dot(matrix1, matrix2)
print(product)


[[0.81460778 0.33806974]
 [1.1614789  0.65489865]
 [0.88365569 0.22969119]
 [0.53566317 0.25665331]
 [0.14227154 0.15830879]]
